name: CI/CD PBVM-WEB

on:
  push:
    branches: [ "develop" ] # Chạy khi bạn push vào nhánh main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # 1. Đăng nhập vào kho chứa (ACR)
      - name: Log in to Azure Container Registry
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.ACR_LOGIN_SERVER }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      # 2. Build Docker Image và Push lên ACR
      - name: Build and push Docker image
        run: |
          docker build -t ${{ secrets.ACR_LOGIN_SERVER }}/web-novel-app:${{ github.sha }} .
          docker push ${{ secrets.ACR_LOGIN_SERVER }}/web-novel-app:${{ github.sha }}

      # 3. Đăng nhập vào Azure để ra lệnh Deploy
      - name: Log in to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # 4. Yêu cầu Web App lấy Image mới về chạy
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'web-novel-app' # Tên Web App của bạn
          images: '${{ secrets.ACR_LOGIN_SERVER }}/web-novel-app:${{ github.sha }}'
